# Use an official Python runtime as a parent image
FROM python:3.10.9-slim

# Set the working directory to /app
WORKDIR /backend_app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME fastapi_app

# Run main.py when the container launches
#CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

CMD ["python", "app.py"]
